version: '3.3'

services:
  postgres:
    container_name: evolution_api_postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=evolution
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5433

  api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.0
    platform: linux/amd64
    restart: always
    depends_on:
      - postgres
      - redis
    networks: 
      - evolution-net
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - .env
    command: ['node', './dist/src/main.js']
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

volumes:
  evolution_instances:
  evolution_store:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  todo-app-data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
