spring:
  application:
    name: rag-open-ai-tcc
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: com.tcc.rag_open_ai_tcc.config.CustomPostgreSQLDialect

server:
  port: 8081

evolution-api:
  url: http://localhost:8080
  key: 0417bf43b0a8969bd6685bcb49d783df

#resilience4j:
#  retry:
#    instances:
#      EvolutionApiClient:
#        maxAttempts: 3
#        waitDuration: 2s
#        retryExceptions:
#          - com.tcc.rag_open_ai_tcc.exceptions.EvolutionApiException