version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rag_db
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - tcc-net
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres_data:

networks:
  tcc-net:
    driver: bridge